# Generated by Django 3.1.3 on 2020-11-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('notice_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_file', models.FileField(upload_to='')),
                ('marks', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'assign',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('fac_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fac_pwd', models.CharField(max_length=100)),
                ('fac_name', models.CharField(max_length=100)),
                ('fac_email', models.CharField(max_length=100)),
                ('fac_mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('stud_pwd', models.CharField(max_length=100)),
                ('stud_name', models.CharField(max_length=100)),
                ('stud_email', models.CharField(max_length=100)),
                ('stud_mobile', models.IntegerField()),
                ('sem_No', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('cgpa', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=50)),
            ],
        ),
    ]
