# Generated by Django 3.1.3 on 2020-11-15 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201115_1436'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assignment',
            table=None,
        ),
    ]
