# Generated by Django 3.1.3 on 2020-11-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20201115_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='materials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_title', models.CharField(max_length=100, verbose_name='ENTER TITLE:')),
                ('lec_pdf', models.FileField(upload_to='', verbose_name='ENTER DOCUMENT:')),
            ],
        ),
    ]
