# Generated by Django 3.1.3 on 2020-11-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_materials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materials',
            name='id',
        ),
        migrations.AlterField(
            model_name='materials',
            name='lec_title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='ENTER TITLE:'),
        ),
    ]
