# Generated by Django 3.1.3 on 2020-11-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20201115_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('faq_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fac_qsn', models.CharField(max_length=100)),
                ('faq_asn', models.CharField(max_length=100)),
            ],
        ),
    ]
