# Generated by Django 3.1.3 on 2020-11-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feed_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('reg_no', models.CharField(max_length=100)),
                ('descp', models.CharField(max_length=100)),
            ],
        ),
    ]
