# Generated by Django 3.1.3 on 2020-11-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20201115_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='descp',
            field=models.CharField(max_length=100, verbose_name='message:'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reg_no',
            field=models.CharField(max_length=100, verbose_name='enter your rollno:'),
        ),
    ]
