# Generated by Django 3.1.3 on 2020-11-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_assignsub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='fac_qsn',
            new_name='faq_qsn',
        ),
    ]
