# Generated by Django 3.1.3 on 2020-11-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20201116_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(upload_to='', verbose_name='ENTER FILE:'),
        ),
    ]
