# Generated by Django 3.1.3 on 2020-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20201116_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_credits', models.CharField(max_length=100)),
                ('course_type', models.CharField(max_length=100)),
                ('course_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('no_of_sec', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='faculty',
            name='dept_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
