# Generated by Django 3.1.3 on 2020-11-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_course_course_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignsub',
            name='id',
        ),
        migrations.AddField(
            model_name='assignsub',
            name='assignment_no',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
